oe-alliance/enigma2-plugins

autotimer/src/AutoTimer.py

The last version did not properly distinguish between the three possible values for the parameter "searchForDuplicateDescription":
0 = "Title"
1 = "Title and Short description"
2 = "Title and all descriptions"
Even worse if searchForDuplicateDescription was set to 0 in the options the similarity check always returned FALSE.
I have updated the code to fix these issues.
Im Code gibt es aber nur ein "if timer.searchForDuplicateDescription > 0 or force:".
Das heiﬂt zwischen den Suchmethoden "Title and Short description" und "Title and all descriptions" wird gar nicht unterschieden.
Schlimmer ist aber, dass bei der Suchmethode "Title

Update AutoTimer.py to fix checkSimilarity method

---

networkbrowser/src/MountManager.py

In Change hostname, the current code reads the whole /etc/hostname
as the text for the VirtualKeyBoard and doesn't strip the newline(s).
That means that there's a "hidden" newline in the VirtualKeyBoard
text that has to be skipped back over before the text can be edited.
This commit reads only the first line of /etc/hostname
(as does the Busybox hostname -F /etc/hostname) and strips the
newline from it before passing it to VirtualKeyBoard.
The newline is added back when /etc/hostname is written.

[MountManager] Handle newline in /etc/hostname correctly

---

epgsearch/src/EPGSearch.py

The "stripped copy of EPGSelection.__init__" in EPGSearch didn't
include the initialisation of EPGSelection.HelpableScreen, so there
was no connection to the HELP screen.
Added a call to HelpableScreen.__init__() and so made the HELP
screen accessible.

Enable EPGSearch HELP screen

---

imdb/src/plugin.py

15:54:30.948 {   } Screens/InfoBarGenerics.py:204 actionA KEY: 358 0 KEY_INFO INFO
15:54:30.951 {   } Components/ActionMap.py:46 action action ->  WizardActions info
15:54:31.896 { D } Traceback (most recent call last):
15:54:31.896 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
15:54:31.897 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/MediaPortal/resources/simpleplayer.py", line 1464, in openMovieinfo
15:54:31.915 { D }     self.session.open(IMDB, title)
15:54:31.915 { D }   File "/usr/lib/enigma2/python/mytest.py", line 321, in open
15:54:31.917 { D }     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
15:54:31.917 { D }   File "/usr/lib/enigma2/python/mytest.py", line 259, in instantiateDialog
15:54:31.918 …

fix possible bsod

---

epgsearch/src/EPGSearch.py

When `config.usage.multibouquet.value` is `False`, zapping using OK in `EPGSearch` hangs the UI, because the serviceref search goes into an infinite loop.
When `config.usage.multibouquet.value` is `True`, zapping using OK in `EPGSearch` can change bouquets, even if the current bouquet contains the service being zapped to.
The two commits in this pull request fix those two problems.
More details of the problems and the fixes are in the commit notes.
These two problems have been found in other parts of the Beyonwiz clone of the enigma2 UI (e.g. in `RecordTimer._zapToTimerService()`. It's possible they are also to be foind in other clones and in other plugins.

Fix epgsearch zap

---

epgsearch/src/EPGSearch.py
epgsearch/src/EPGSearchSetup.py
epgsearch/src/__init__.py

Add the ability for the user to specify the scope of the EPG search (all services/all bouquets/current bouquet/current service/ask user").
Fix bug that prevented setting description text from being displayed.
Tidied up `ActionMap` actions and help. Tidied up UI text.
Allow direct access to search history with long-YELLOW.
Detailed description of changes in the commit logs.
[EPGSearchSetup] Remove unused "status" widget
[EPGSearchSetup] Add "description" widget
EPG Search: Allow specification of search scope
EPG Search: Allow "ask user" specification of search scope
[EPGSearchSetup] Only show "ask user" specification of search scope when active
EPG Search: ActionMap and text cleanup
[EPGSearch] Add search history access on long-YELLOW

Add epg search search scope

---

epgsearch/src/EPGSearch.py
epgsearch/src/EPGSearchSetup.py

A crash fix, tweak flag handling to ignore irrelevant flags, make skin name lists in `EPGSearch` re-user the skin name already set in the class, and add the ability to override the Setup skin in `EPGSearchSetup`.
Also add "Setup" entry to "ask user" search scope menu to allow the user to modify oter search settings before running the search.
These changes were intended to have been in add-epgsearch-searchscope.

Epgsearch searchscope fixup

---

epgsearch/src/EPGSearch.py
epgsearch/src/EPGSearchSetup.py
epgsearch/src/__init__.py

Optionally add an orbital position to each search result.
Code cleanup to simplify `EPGSearchList`.
Allow AutoTimer icons to be displayed if `EPGList` supports their display.

EPG Search: Add optional orbital position to search list

---

epgsearch/src/EPGSearch.py
epgsearch/src/EPGSearchSetup.py
epgsearch/src/__init__.py

Add code to set the eEPGCache.search() search type and search case
sensitivity from settings.
Displays the IceTV logo for timers set by IceTV, if the implementation of EPGList supports them.

Add search type/case sensitivity settings and IceTV timer icons

---

epgsearch/src/EPGSearch.py
epgsearch/src/plugin.py

[EPGSearch]
Add default parameter openHistory to __init__(). Defautls to False.
When True, EPGSearch opens the EPG Search History popup to allow
search from the history instead of initiating an immediate search.
[plugin]
Add searchhistory() function for calling from PluginDescriptors to
allow startup in the EPG Search History popup.
Add PluginDescriptors to call the searchhistory() function from the
Event Info popups from live TV and from Screens.ButtonSetup
(WHERE_EVENTINFO), and from the MENU button in Screens.MovieSelection
(WHERE_MOVIELIST).
In Screens.ButtonSetup, the normal "search EPG" can be referenced
as "Plugins/Extensions/EPGSearch/1" and "search EPG from history..."
can be referenced as "Plugins/Extensions/EPGSearch/2".
Add non-printing characters "\x86" and "\x87" to the …

EPG Search: Allow optional search from search history at startup

---

epgsearch/src/EPGSearch.py

Redisplay the list after the "Show orbital position" setting
changes, so that the change is reflected in the search list immediately.

[epgsearch] Redisplay search list after orbpos setting changes

---

epgsearch/src/EPGSearch.py

Minor bug fixes to fix:
- Crash when the image's `EPGSelection` doesn't inherit from `HelpableScreen`.
- Use correct serviceref as "current service" when the currently playing service had isGroup flag set.
- Call `self.recalcEntrySize()` after `self["list"].l.setList()` instead of before it, so that the scrollbar width is properly set before `self.recalcEntrySize()` asks for the list width.
- Use the parent class's list width instead of the full list width.

Epgsearch minor bugfixes

---

epgsearch/src/EPGSearch.py

Expand alternatives (sref.flags & eServiceReference.isGroup) when
scanning bouquets to create search filters.

[epgsearch] Handle alternatives correctly

---

epgsearch/src/plugin.py

Replace the use of "\x86" / "\x87" to control the sort ordet of plugins,
because they don't seem to work in translations.
Use _("%sTranslated String) % "\x86" in the code instead: printf format
codes should work better.

[epgsearch] Tweak ordering of translated strings

---

epgsearch/src/EPGSearch.py
epgsearch/src/plugin.py

[epgsearch] Make searches more comprehensive and accurate
Search the EPG on serviceref and then filter on the search string to
preserve path and name information in the servicerefs searched on.
Path and name information is lost when eEPGCache::search() is
used for the search.
Change the "all services" search so that it searches all the
servicerefs in "all bouquets" as well as the servicerefs in lamedb.
[epgsearch] Search TV bouquets in TV mode and Radio bouquets in Radio mode
Also make code robust to ChannelSelection.instance not being set.
[epgsearch] Make orbpos column left-adjusted
Also slightly wider to accommodate a VIX skin.
[epgsearch] Make zap() work correctly in Radio mode
[epgsearch] Fix button assignment in MovieSelection
Allow both WHERE_MOVIELIST PluginDescriptors to appear …

Epgsearch misc fixes

---

epgsearch/src/EPGSearch.py
epgsearch/src/EPGSearchSetup.py
epgsearch/src/__init__.py

Allow searches to be filtered by including or excluding sources by orbital position for satellites, or on whether the broadcasts are DVB-T or DVB-T.
Also use RIGHT/LEFT to change "Length of history" instead of using the numeric keys and tidy up when the history list is trimmed.

Filter searches by orbpos/source & fix history trimming

---

advancedmovieselection/src/AdvancedMovieSelectionSetup.py
mytube/src/plugin.py
networkbrowser/src/MountEdit.py
networkbrowser/src/UserDialog.py
networkbrowserpli/src/MountEdit.py
networkbrowserpli/src/UserDialog.py

This change makes the VKeyIcon a Boolean and fixes the cross definitions between a Boolean and a Pixmap across the code base.
- [AdvancedMovieSelectionSetup] Make VKeyIcon a Boolean 
- [plugin] Make VKeyIcon a Boolean
- [MountEdit] Make VKeyIcon a Boolean
- [UserDialog] Make VKeyIcon a Boolean
- [MountEdit] Make VKeyIcon a Boolean
- [UserDialog] Make VKeyIcon a Boolean
This pull request may have implications for skins that don't use the standard VKeyIcon bpplean coding.

Fix VKeyIcon

---

audiosync/src/AC3delay.py

Problem found on Beyonwiz T4 with HDMI IN.
When HDMI IN is the service being viewed live, enter
the "Select audio track" popup (long-AUDIO
on Beyonwiz image, may be short-AUDIO in other images).
Press BLUE Audio Sync, crash.
The problem is due to `eServiceHDMI::audioTracks()`
returning `None` in Python. This condition is not correctly tested for
in `AC3delay.getAudioInformation()` and the UI crashes
when `oAudioTracks.getCurrentTrack()` is called when
`oAudioTracks is None`.
The problem is also likely to occur when Xine services are
being played, since `eServiceXine::audioTracks()` also returns None.
The fix ensures that `oAudioTracks.getCurrentTrack()` is only
called when `oAudioTracks is not None`, and that other values
normally set in `AC3delay.getAudioInformation()` are given
sensible …

Fix crash when Audio Sync settings are selected on a HDMI IN service

---

autotimer/src/AutoTimer.py

were excluded by day-of-week, time-of-day or wrong-channel. Previously
this was, essentially, the count of pre-existing timers.
Hence the stats produced a greatly (and meaningless) inflated total for
matching events.
This change adds a self.existing array to handle (and report) those,
leaving the skipped array is for items skipped for other reasons.
This reverts the stats counts to meaningful values.

Recent changes had added all title matches into skipped, even when they

---

epgsearch/src/EPGSearch.py

The "r2 = self.datetime_rect" and "r3 = self.orbpos_rect" rectangles have their heights incorrectly defined as the height of the "r1 = self.weekday_rect" rectangle.
Given that the heights are currently all the same this error has had no consequence.  This correction is to protect any future cases where this may no longer be the case.

Correct the rectangle height definitions

---

autoresolution/src/plugin.py

Should still handle the original modes_available if it is there

Handle modes_available disappearing from OpenVix AVSwitch.

---

autoresolution/src/plugin.py

The additional 1080p* options [default_choices] have been re-instated (they were unintentionally omitted from the previous change).
Now fixed up for 720p50 to show for 720p50 signal.

Added 720p50 handlers and some 2160p changes

---

epgsearch/src/EPGSearch.py

This change supports the new columnar time formats adopted by the Beyonwiz build and under consideration by OpenViX.  Other builds should see no difference.

[EPGSearch] Update start/end times to columnar fmt

---

moviecut/src_cc/mcut.cc

A few fixes for inconsistent code indentation, uninitialised variables and an operator precedence issue.

Fix mcut warnings and operator precedence bug

---

autotimer/src/AutoTimer.py

If an `AutoTimer` with "description" Search type is created with no
service or bouquet restrictions, the timer won't match events that
contain the description text.
_Replication steps_
In any convenient way, create an AutoTimer with "description" Search
type and a "Match title" string that is known to match at least one
instance of a program. Set its Restrict to specific bouquets setting
to a bouquet that contains the program (e.g. Terrestrial TV LCN).
Verify that the AutoTimer matches programs as expected using
MENU>Preview in the AutoTimer list screen.
Remove the restriction in Restrict to specific bouquets.
MENU>Preview now matches no programs.
_Fix_
Remove excess indentation in part of `AutoTimer.parseTimer()` loop
over all services in all bouquets.

Fix AutoTimer "description" search failure if no service restrictions

---

epgsearch/src/EPGSearch.py

This code used to call a reclass of the VirtualKeyBoard called NTIVirtualKeyBoard that lives in the System Toolkit plugin.
The NTIVirtualKeyBoard appears to have been used to implement SMS data entry into an older version of the VirtualKeyBoard.  That functionality is now native in the current VirtualKeyBoard.
This change addresses a data entry issue in the EPGSearch functionality where the cursor position is not correctly updated during SMS style data entry.

[EPGSearch.py] Use the system VirtualKeyBoard

---

epgsearch/src/EPGSearch.py

Prime the NewSearch search string with previous search string.  This allows users to make multiple related searches without all the text entry time.
If a totally new search is required then simply select the CLR button first.
Thank you Rob for the suggestion.

[EPGSearch.py] Initialise NewSearch string

---

imdb/src/plugin.py

The HTML for the IMDb user ratings display has changed.
The change causes most series Details displays (e.g. for Castle)
to fail with a ValueError: could not convert string to float
exception.
Some (especially older) movies fail in the same way (e.g. Pocketful
of Miracles)).  Newer movies often don't crash, but display the
MetaCritic rating instead of the IMDb user rating. This often shows
impossibly high ratings (e.g. 72/10 for Full Metal Jacket).
Tweak the user ratings regular expression match to correctly extract
the user rating.

Tweak user ratings pattern match

---

epgsearch/src/EPGSearch.py

This PR fixes a crash that occurs when using EPGSearch's _import from EPG_ screens, when `EPGSelection` has been extended to have a list of skin names in `self.skinNames`. This isn't an issue with the current EPGSelection, but there is work in OpenVix to rationalise the EPGs, which also simplify the skin names and require a list to be used for backwards compatibility.

Fix crash when EPGSelection has list in skinNames

---

imdb/src/plugin.py

If the IMDb text contains any of the strings "\c", "\n", "\r" or
"\t", they are interpreted as escape sequences by
eTextPara::renderString().
Unfortunately, renderString() does not provide a clean way to escape
the "\" character, so the "\" that is to appear in the text is
separated from the alpha character by a <CR>, which is a no-op in
eTextPara::renderString().
So, for example, "\c" in the IMDb text is transformed into "\<CR>c",
which then displays as "\c" on the screen.
There really should be a clean way to escape the escape character
in renderString().
The change is prompted by real data in IMDB. In the Trivia section
the movie "The Core" (2003) a commenter uses "\" where "/" would
normally be used: "In the 1950s\60s, during the design\construction
of the SR-71 Blackbird ...". The …

[imdb] Fix font escape sequences

---

autotimer/src/AutoTimer.py
autotimer/src/AutoTimerConfiguration.py
autotimer/src/AutoTimerEditor.py

1. Provide a method to edit the autotimer given a timer.
1. persisting the autotimer's `id` in autotimer.xml
1. storing `autoTimerId` on each timer that it creates
1. Also provide a method to create an autotimer from a timer
Note that 3 requires changes in enigma2's [RecordTimer.py](https://github.com/SimonCapewell/enigma2/commit/6ef4cb2cc4fc8abeda26f35aa649f6921454f7f5#diff-0f321e0c10bf545be5c64a41d09d6732) to save the new attribute to timer.xml
This is a companion piece to go with the work in https://github.com/SimonCapewell/enigma2/tree/epg-custom-buttons to enable enter editing an autotimer from the EPG screens in the same way you can edit a standard timer.

Enhancements to allow editing a timer's autotimer

---

epgrefresh/src/EPGRefreshChannelEditor.py
epgrefresh/src/EPGRefreshConfiguration.py

Changes to ActionMaps in recent changes to ViX ConfigListScreen
caused problems in ViX 5.4.001.002.
An ActionMap in EPGRefreshServiceEditor updated to -2, so that its
actions override the corresponding actions in ConfigListScreen.
Otherwise the save and cancel actions in ConfigListScreen are used
insted of those in EPGRefreshServiceEditor.
Added closeRecursive() methods to EPGRefreshConfiguration and
EPGRefreshServiceEditor to override those methods on the cancel
action in versions of ConfigListScreen that have them.
Backwards compatibility tested in ViX 5.4.000.004, which predates
the ConfigListScreen changes.

[EPGRefresh] Make ActionMaps compatible with new ConfigListScreen

---

vps/src_py/Modifications.py
vps/src_py/Vps_setup.py

Simplify arg counting code.
Bump version to 1.31.

Pass on all incoming parameters on intercepted calls.

---

vps/src_py/Modifications.py
vps/src_py/Vps_setup.py

Also includes a comment (but *not* code) change on the new_TimerEntry_createSetup() call.
And trims all lines (the dev version already has this).

Cater for TimerEntryBase usage in TimerEntry refactoring.

---

vps/src_py/Modifications.py
vps/src_py/Vps_check.py

Use relative syntax for local imports.
Should always have been used.
Needed for Py3.

Use relative syntax for local imports.

---

epgsearch/src/EPGSearch.py

Zapping whilst in playback switches to live TV, but leaves the movie
infobar open. Reuse EPGSelection's zapExit function (if available) to do
the zap.

EPGSearch zapping breaks the movie infobar state.

---

imdb/src/plugin.py

Launching IMDb, then finding a channel and event to lookup is
a tortuous usage pattern.
Typical usage now is far more likely to one of the following
- launching IMDb from the EPG/Event view
- launching IMDb from the Infobar in live TV
- launching IMDb from the infobar in playback

Remove anachronistic IMDb "Select from EPG" option

---

autotimer/src/AutoTimerConfiguration.py

Output space-separated tags correctly (#418)
This change outputs autotimer tags individually instead of providing a space-separated list which splits space-separated tags incorrectly.
`<e2tags>` is kept so as not to break existing consumers.

[AutoTimer] Output space-separated tags correctly (#418)

---

vixautotimer/src/AutoTimerConfiguration.py

Output space-separated tags correctly
This change outputs autotimer tags individually instead of providing a space-separated list which splits space-separated tags incorrectly.
is kept so as not to break existing consumers.

Output space-separated tags correctly

---

autotimer/src/AutoTimerResource.py

This change re-enables returning ALL matching AutoTimers when no `id` is passed

Restore test/simulate ALL

---

remotetimer/src/plugin.py

- bugfix that avoid permanent spinner when username and/or password are empty.
- special thanks to **@Snoete** for detailed testing under openATV 6.4 and 7.0

[remoteTimer]

---

simplerss/src/RSSPoller.py

Resetting the libraries used:
'**twisted.web.client import getPage**' flies out again
'**from twisted.web.client import Agent, readBody & from twisted.internet import reactor**' comes back in

[SimpleRSS] Correction of RSSPoller.py

---

ardmediathek/src/ard.py

Fix crash when no image is available

ARD Mediathek

---

imdb/src/plugin.py

The translation for "Trivia" was renamed; a translation for "Seasons" was added.
Replace an assumed CP1252 ellipsis with the proper equivalent.

[imdb] Update labels

---

imdb/src/plugin.py

A search for "Catch And Release" failed; doing it in the browser shows it wants a captcha test.  Placing "s" before "q" is enough to make it work again.

[imdb] Fix a query issue

---

autotimer/src/AutoTimer.py
autotimer/src/AutoTimerEditor.py

- Fix typo
- Support openatv margins(margin_before, zap_margin_before, margin_after, zap_margin_after) as default on editor fix(https://github.com/oe-alliance/enigma2-plugins/issues/625)
- Support openatv zap_has_endtime

Support openatv margins

---

epgsearch/src/EPGSearch.py

This change places the cursor on the search result entry closest to the current time.
This change does not cause past events to be faded out as happens in Single-channel EPG.

[EPG Search] Jump to search result nearest current time

---

weatherplugin/src/plugin.py

Updated plugin.py

---

imdb/src/plugin.py

Fixes the `attributes` error (closes #683); recognises a review without a rating; fixes and improves getting the storyline; adds IMDb videos to the context menu.

IMDb update
