autotimer/src/AutoTimerList.py

http://www.opena.tv/skins/4708-metrixhd-default-skin-openatv-4-0-bugs-post139332.html#post139332

[AutoTimerList.py] fix "timeframe" position

---

networkbrowser/po/es.po

Updated spanish translation and added some strings that weren't in the original file.

[NetworkBrowser] Updated spanish translation

---

autotimer/po/el.po

Greek translation for Autotimer plugin 18/6/2015

Greek translation for Autotimer plugin 18/6/2015

---

autoresolution/po/el.po

Greek translation update for Autoresolution plugin

Greek translation update for Autoresolution plugin

---

pluginsort/po/el.po

Greek translation for pluginsort

Add Greek translation

---

networkbrowser/po/el.po

Greek translation for Network Browser

Greek translation for Network Browser

---

epgsearch/src/EPGSearch.py

Also tidied up the column width calculation generally.

[EPGSearchList] Calculate orbital position column width from the font size

---

epgsearch/src/EPGSearch.py

Sometimes DVB servicerefs in bouquets have paths set that aren't relevant
for search filtering.
Remove the serviceref paths in all DVB servicerefs (ignoring the
"scrambled" bit), whether they originate from the EPG, from the bouquets
or from the current service serviceref.
Package the serviceref normalisation in method _normaliseSref() and
remove the old searchFilterMatch() function.

[EPGSearch] Fix problems with serviceref matching/filtering

---

epgsearch/po/el.po

Greek translation for EPG Search 17/8/2016

Greek translation for EPG Search 17/8/2016

---

epgsearch/src/EPGSearch.py

For searches with a small nymber of services in the filter, use the
previous search algorithm of extracting each service's EPG data and
doing the event name match in python.
For services with a larger number of services in the filter, use
the low-leven EPG search by name and filter out the unwanted results.
Display a "Searching.." text item in the list while the search is
running to give feedback to the user when a search taks a long time
to run.

[epgsearch] Speed up searches with large numbers of services

---

autotimer/src/AutoTimer.py

for text that is stored in the timer-log-file

[AutoTimer.py] update for translation

---

autotimer/src/AutoTimer.py

Reverts oe-alliance/enigma2-plugins#114

Revert "[AutoTimer.py] update for translation"

---

autotimer/po/de.po

Reverts oe-alliance/enigma2-plugins#115

Revert "[autotimer] update de.po"

---

imdb/src/plugin.py

Tidy up some of the usage in IMDB Search.
Note that the changes to the `"IMDb can not get Movie Information"` `MessageBox` popups are for code that is unreachable in the current code.

[imdbsearch] Text cleanup

---

imdb/po/IMDb.pot
imdb/po/el.po

IMDb pot renewal and Greek translation added

IMDb pot renewal and Greek translation added

---

autotimer/src/AutoTimer.py

add log entry for the first created timer from autotimer
if autotimer changed the timer, it is so easier to see why and see the diffrent time

[AutoTimer] add log entry for the start time of timer

---

epgsearch/src/EPGSearch.py

- [EPGSearch.py] PEP8 cleap up and tidy up
- [EPGSearch.py] Add option for dual time display and custom date / time formats
This pull request matches with soon to be filed enabling pull requests in the OpenViX repository for the configurable date and time formats which will then feed the Beyonwiz repository.
At the moment I am only aware of the Beyonwiz version of Enigma2 using both start and end times for the EPG displays.  This change will allow the EPGSearch to display results in a matching format.

Enhance EPGSearch

---

autotimer/src/AutoTimer.py

These provide no useful information as they do not mention which timer is involved - they just fill up the debug log.
Also added [AutoTimer] tags to 3 of them, in case anyone wishes to enable them later.

Comment out 4 debug lines.

---

epgsearch/src/EPGSearch.py

This change matches the time column alignments with the alignments used in EpgList.py.

[EPGSearch] Match column alignments with EpgList

---

moviecut/src_py/plugin.py

Replace the global queue with a task, which provides better management,
including progress (estimated based on the old file size and ratio of
the new and old lengths) and the ability to cancel.  Remove the initial
background message; the completed message will timeout after 10 seconds.

[moviecut] Turn into a task

---

epgsearch/src/EPGSearch.py
epgsearch/src/__init__.py

Add regex as option, just as case and case-insensitive

Add Regex as option

---

imdb/src/plugin.py

Various fixes to the regular expressions that extract data from IMDb HTML data to deal with changes in the HTML produced by IMDb, character encoding improvements to better display non ASCII characters and allow the full title information to be displayed in the Title Menu screen.
Make improvements to the text layout, especially in the Extra Info screen.
Translate some untranslated UI strings.

Screen scraper update

---

imdb/src/plugin.py

Allow IMDb searches on the current selection in the MovieSelection screen and
allow IMDb setup to be accessed from the plugin browser.

Add plugin descriptors for movie selection and setup

---

epgsearch/src/EPGSearch.py

Fixed a crash and lack of functionality similar to a recent fix in the IMDb search plugin.

[epgsearch] Fix EPG search - Import from EPG

---

epgsearch/src/EPGSearch.py

<parameter name="EpgListIcon" value="2,12,25,25,2"/>
-> posx, posy, sizex, sizey, gap

[EPGSearch] add skin parameter 'EpgListIcon'

---

imdb/src/plugin.py

Update the regular expressions that extract the show title, the storyline,
the user reviews and the cast list.

[IMDb] Update screenscraping regular expressions

---

imdb/src/plugin.py

Change ratingmask to match changes in IMDb HTML.

Fix IMDb user ratings

---

autotimer/po/AutoTimer.pot
autotimer/po/de.po
autotimer/src/AutoTimer.py
autotimer/src/AutoTimerList.py
autotimer/src/AutoTimerSettings.py
autotimer/src/__init__.py
autotimer/src/plugin.py
autotimer/src/setup.xml

[autotimer] show bouquets in timerlist
[autotimer] fix for skipped autotimer with same name
[autotimer] add option for double timer on different services 
[autotimer] version increased

[autotimer] update

---

networkbrowser/po/it.po

Added many new lines. Revieed some previous ones.

[translation] NetworkBrowser Italian language translation - update

---

vps/po/it.po

Reviewed some lines. Edited a typo.

[translation] Italian language translation-update

---

epgsearch/po/it.po

First update after some years. 
Added many lines never translated before.

[translation] Italian language translation for Enigma2-Update

---

vps/src_py/Vps_check.py
vps/src_py/Vps_setup.py

Use different built-in skin parameters for large screens.

---

vps/src_py/Modifications.py
vps/src_py/Vps_setup.py

Simplify arg counting code.
Bump version to 1.31.

Pass on all incoming parameters on intercepted calls.

---

vps/src_py/Modifications.py

Cater for TimerEntryBase usage in TimerEntry refactoring.

Cater for TimerEntryBase usage in TimerEntry refactoring.

---

vps/po/it.po

Reviewed several messages. Optimized the size of the file in order to be lighter, particularly for old boxes, removing references to pyton code.

 [translation] Italian language translation-update

---

autotimer/src/AutoTimer.py

Tentative fix for #395 on python3 branch.

Autotimer py3

---

imdb/src/plugin.py

Remove unused imports and code.
Use 'r' prefix for some regex strings.
Trim the html before working on it.
Strip out svg tags, too.
Restore the usage of fontescapes.
Restore the ordering of the "old version" patterns.
Improve the efficiency of the "new version" patterns.
Use a smaller "nospace" list instead of "addspace".
Fix movielistSearch.
Treat "director" & "writer" same as "creator" (bracketed items).
Don't limit the cast to 16 names.
Fix "new version" user review, keywords and genre.
With the genre fix restore the category name from the pattern.
Add episode count; "new version" uses season count.
Don't show outline if it starts the synopsis.
Remove the double blank after outline and synopsis.
Use newlines (p tags) with "new version" quotes.
Put the title & author of the review on …

[imdb] Fixes and improvements

---

imdb/src/plugin.py

This applies 2 missing updates to the python3 branch - this updated version has been applied to latest OpenViX python3 image and testers have OK'ed the results.

Python3 - cherry picks misssing update from SimonC and also applies latest change from Adoxa

---

imdb/src/plugin.py

Allow other attributes in the pattern for the poster.
Update the URL used to access IMDb.

IMDb poster

---

easymedia/src/plugin.py

- adapted to OE-Alliance plugins
- working under Python2+3

[EasyMedia] Adaption to OE-Alliance and Py2+3

---

imdb/src/plugin.py

This prevents the 308 redirect message.

[imdb] Include trailing slash in find URL

---

imdb/src/plugin.py

Storyline: skip if none;
Production company: end tag could be "span";
Cast: allow for a missing character name.
There might not be news, stop at the "contribution" section.

[imdb] Pattern updates

---

easymedia/src/plugin.py

[EasyMedia] update

---

imdb/src/plugin.py

Sound mix: add separators;
stop at taboola if there's no contribution section.

IMDb updates

---

dyndns/src/plugin.py
genuinedreambox/src/plugin.py
mediadownloader/src/MediaDownloader.py
partnerbox/src/PartnerboxFunctions.py
remotetimer/src/plugin.py
rsdownloader/src/plugin.py
webcamviewer/src/PictureScreen.py
webinterface/src/WebComponents/Sources/TPMChallenge.py

- b64encode / b64decode fixed in order to be compatible to Py2 and Py3

[enigma2-plugins] 

---

remotetimer/src/plugin.py

[remotetimer]

---

imdb/src/plugin.py

Adjust to the change in class names.

[imdb] Update patterns

---

partnerbox/src/PartnerboxSetup.py
partnerbox/src/plugin.py
partnerbox/src/skin_FHD.xml
partnerbox/src/skin_HD.xml

- new skin_FHD properly upscaled from skin_HD
- now skins can be modified without restarting GUI

[Partnerbox] improvements (skins + code)

---

showclock/po/fi.po

finnish_translation

---

simplerss/src/RSSFeed.py
simplerss/src/RSSPoller.py

now runs under Python 2 and Python 3

[SimpleRSS] Update

---

esame/src/stonefield.py

[eSame] bugfix

---

unwetterinfo/src/plugin.py

- bugfix: no more crashes when menu remain empty (AT-homepage was completely changed)
- deprecated 'twisted.web.client.downloadPage & .getPage' replaced by current 'twisted.internet.reactor.callInThread'
- imports were cleaned up
- tiny skin modification

[UnwetterInfo] bugfix & maintenance

---

imdb/CONTROL/control
imdb/src/plugin.py

Replace the regex searches with JSON data that's included in the page, including the translations provided by IMDb.  The storyline & tagline are downloaded separately.
Use requests for downloads (resolves #528); update the dependents.
Press MEDIA to download and display a bigger poster; press TEXT to display a synopsis (if available; this may require a skin change to add "VKeyIcon").
Save is always available (parameter still exists, but is ignored), using "/home/root/logs/imdb" if no path is specified.  Use "-TITLEID" instead of ".imdbquery2".  HTML will save the poster; text will be similar to how it's displayed; text with poster will use the big poster if it's been downloaded, otherwise the full-size poster will be retrieved.
quoteEventName stopped using the safe list, remove it.
Add …

[imdb] Big update

---

imdb/src/plugin.py
imdb/src/setup.xml

IMDb modified their search results, JSON data is now present. Add an option to include episodes in the menu.  Resolves #549.

[imdb] Fix search results

---

easymedia/src/plugin.py

- menu 'add / remove plugin' fixed. **special THX** to **jbleyel @ openATV**

[EasyMedia] bugfix

---

merlinmusicplayer/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' replaced by current 'twisted.internet.reactor.callInThread'

[MerlinMusicPlayer] changeover to twisted.internet.reactor.callInThread

---

shoutcast/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' replaced by current 'twisted.internet.reactor.callInThread'

[SHOUTcast] changeover to twisted.internet.reactor.callInThread

---

bmediacenter/src/GlobalFunctions.py
bmediacenter/src/MC_AudioPlayer.py
bmediacenter/src/MC_Filelist.py
bmediacenter/src/MC_PictureViewer.py
bmediacenter/src/MC_Settings.py
bmediacenter/src/MC_VLCPlayer.py
bmediacenter/src/MC_VideoPlayer.py
bmediacenter/src/MC_WeatherInfo.py
bmediacenter/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' & 'getPage' replaced by current 'twisted.internet.reactor.callInThread'

[BmediaCenter] changeover to twisted.internet.reactor.callInThread

---

orfat/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' & 'getPage' replaced by current 'twisted.internet.reactor.callInThread'

[ORFat] changeover to twisted.internet.reactor.callInThread

---

webcamviewer/src/PictureScreen.py
webcamviewer/src/WebcamTravel.py
webcamviewer/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' & 'getPage' replaced by current 'twisted.internet.reactor.callInThread'
- bugfixed: works under Py2+Py3

[WebcamViewer] changeover to twisted.internet.reactor.callInThread

---

merlinmusicplayer/src/plugin.py

fixed: 
nexttitle "b' Title"
play/pause work now
minor fix 
Regards

Fix play/pause and NextTitle ('b)

---

simplerss/src/GoogleReader.py
simplerss/src/RSSFeed.py
simplerss/src/RSSList.py
simplerss/src/RSSSetup.py

- DEPRECATED 'twisted.web.client.downloadPage' & 'getPage' replaced by current 'twisted.internet.reactor.callInThread'
- some bugfixes

[SimpleRSS] changeover to twisted.internet.reactor.callInThread

---

imdb/src/plugin.py

IMDb now requires these in order to function correctly.

[imdb] Set user-agent and session-id

---

ofdb/src/plugin.py

- DEPRECATED 'twisted.web.client.downloadPage' replaced by current 'twisted.internet.reactor.callInThread'
- skins overworked
- code overworked

[OFDb] changeover to twisted.internet.reactor.callInThread

---

bmediacenter/po/de.po
filebrowser/po/de.po

(Filebrowser) and (bMediacenter) update de.po

---

bmediacenter/po/de.po

[bmediacenter]

---

birthdayreminder/src/BirthdayNetworking.py
birthdayreminder/src/BirthdayReminder.py

- bugfix CSV import/export, boxes broadcast and saving of birthdaytimer
- some internal code improvements

[BirthdayReminder] some bugfixes

---

ardmediathek/src/ard.py

ARD Mediathek 1.5

---

birthdayreminder/src/BirthdayReminder.py

[BirthdayReminder] tiny bugfix

---

autotimer/src/AutoTimerEditor.py
autotimer/src/AutoTimerResource.py

Make the check in both the enigma2 GUI and on additions/updates from OpenWebIF.

Check that the AT text filters are valid regexes.

---

moviecut/src_cc/mcut.cc

[MovieCut]

---

epgexport/src/plugin.py

- export works now without any troubles
- dependency for python3-requests python3-backports-lzma

[EPGExport] 1.5-r2 bugfix

---

epgexport/po/EPGExport.pot
epgexport/po/de.po
epgexport/po/pl.po
epgexport/src/plugin.py
epgexport/src/skin_HD.xml
epgexport/src/skin_fHD.xml

- changed function: 'Recurring EPG Download' instead of 'Daily EPG Download'
- EPG export fixed: raw format (.xml) and compressed formats (.gz and .xz)
- plugin-own WebIF fixed (test it with: 'BoxIP:Port/LastUpdate.txt')
- code was generally overworked
- skin design was overworked (fHD and HD)
- translations were overworked (DE and PL)
HINT: EPGExport requires dependency for 'python3-requests python3-backports-lzma'

[EPGExport] 1.5-r3 bugfix

---

simplerss/src/plugin.py
simplerss/src/skin_HD.xml
simplerss/src/skin_fHD.xml

- as loaded images are consistently converted to PNGs, as some boxes (e.g. HD51) wrongly display JPGs transparently
- skins improved (makes better use of the available space)
- tiny code improvements

[SimpleRSS] bugfix & tiny code and skin improvements

---

epgexport/src/plugin.py

- now exports all EPG content again

[EPGExport] 1.5-r4 bugfix missing EPG-content

---

imdb/src/Makefile.am
imdb/src/keymap.xml
imdb/src/plugin.py

Repurpose the INFO key to show the first page of user reviews. Spoilers are hidden by default, press INFO again to show them.

[imdb] Show more user reviews

---

epgexport/po/nl.po
epgexport/src/plugin.py
epgexport/src/skin_HD.xml
epgexport/src/skin_fHD.xml

- bugfix: crash caused by os.symlink fixed
- bugfix: recurring call has been corrected
- code was further optimized
- tiny correction in skins
- new Dutch translation added (special thanks to **Snoete @OpenA.TV**)
Many thanks also to **azman @OpenA.TV** and **Südschwede @OpenA.TV** for their thorough cooperation and testing!!!!
HINT: **EPGExport** requires dependency for '**python3-requests python3-backports-lzma**'

[EPGExport] 1.5-r5 update

---

simplerss/po/SimpleRSS.pot
simplerss/po/de.po
simplerss/po/en.po
simplerss/po/en_GB.po
simplerss/po/es.po
simplerss/po/fa.po
simplerss/po/it.po
simplerss/po/lt.po
simplerss/po/nl.po
simplerss/po/sr.po
simplerss/po/tr.po
simplerss/src/feeds.xml
simplerss/src/plugin.py
simplerss/src/skin_HD.xml
simplerss/src/skin_fHD.xml

- pictures in .webp-format are now supported
- tiny code improvements
- tiny skin improvements
- all translations modified accordingly
Thanks to **medici84 @OpenA.TV** for reporting and testing

[SimpleRSS] type 'image/webp' added

---

simplerss/po/SimpleRSS.pot
simplerss/po/de.po
simplerss/po/en.po
simplerss/po/en_GB.po
simplerss/po/es.po
simplerss/po/fa.po
simplerss/po/it.po
simplerss/po/lt.po
simplerss/po/nl.po
simplerss/po/sr.po
simplerss/po/tr.po
simplerss/src/plugin.py
simplerss/src/skin_HD.xml
simplerss/src/skin_fHD.xml

- new: attachments are listed and can be selected and displayed/played (pictures, video and audio files)
- improvement: additional search for enclosures (element 'description')
- tiny skin improvements
- all translations modified accordingly

[SimpleRSS] type 'video/mp4' and 'audio/mpeg' added

---

simplerss/src/plugin.py

- remove posssible dupes in attachments (enclosures)

[SimpleRSS] tiny improvement

---

simplerss/src/plugin.py

- third enclosures-searching method added

[SimpleRSS] improved search for enclosures

---

simplerss/src/plugin.py

- import path option '/tmp/feeds.xml' corrected

[SimpleRSS] tiny bugfix for import path

---

simplerss/src/plugin.py

- removed conversion of picture-urls to HTML-code (has disturbed some picture-downloads)
- some other tiny bugfixes

[SimpleRSS] some bugfixes

---

imdb/po/fi.po

Updated Finnish (fi.po) translation for IMDb

---

epgexport/src/plugin.py

- picon_url was assembled incorrectly

[EPGExport] 1.5-r5 tiny bugfix

---

simplerss/src/plugin.py

- Image sources that only begin with 'http://' are now converted to 'https://'

[SimpleRSS] tiny bugfix

---

autoresolution/src/plugin.py

[autoresolution] change menu setup options

---

weatherplugin/src/plugin.py

Updated plugin.py

---

imdb/src/plugin.py

If SubsSupport is installed add a context menu item (between YTTrailer and the videos) to search for the title (and the original title). Closes #687.

[imdb] Add "SubsSupport search" to context menu

---

imdb/src/plugin.py

The "_ajax" URL stopped working, use the query.
Save the JSON even if it wasn't parsed.

[imdb] Fix reviews

---

networkbrowser/src/NetworkBrowser.py

* This fixes a hostname issue if using a remote DNS, nmap can resolve hostnames if it has access to the local DNS.

[NetworkBrowser]

---

ardmediathek/src/ard.py

- overworked by CommanderData
- commited on behalf of CommanderData

ARD Mediathek update v1.8

---

srfmediathek/src/srf.py

- overworked by CommanderData
- commited on behalf of CommanderData

SRF Mediathek update v0.8

---

imdb/src/plugin.py

Fix "Country of origin" and awards; display all "featured" reviews (and show how many total reviews there are).
The video list would not be reset if you went back to the title menu and selected another movie.

[imdb] Update to match IMDb

---

imdb/po/fi.po

[Translations] Updated Finnish (fi.po) translation
